export default Labels = {
  view_all: 'View All',
  featured_schools: 'Featured Schools',
  blog_detail:'Blog Detail',
  about_us:'About Us',
  add_review:'Add Review',
  who:'I am',
  email:'Email',
  name:'Name',
  message:'Message',
  submit_review:'Submit Review',
  blogs:'Blogs',
  contact_us:'Contact us',
  company_name:'Company Name',
  phone_number:'Phone Number',
  submit:'Submit',
  event_detail:'Event Detail',
  description:'Description',
  event_by:'Event by:',
  registration_required:'Registration Required',
  variable_event:'Is Variable Event',
  free_event:'Is Free event',
  website:'Website',
  venue:'Venue',
  address:'Address',
  postcode:'Postcode',
  city:'City',
  event:'Recent Events',
  faq:'FAQs',
  filter:'Filter',
  reset:'Reset',
  apply:'Apply',
  featured_nursery:'Featured Nursery',
  featured_nursery_group:'Featured Nursery Group',
  featured_school_group:'Featured School Group',
  featured_nannies:'Featured Nannies',
  featured_companies:'Featured Companies',
  featured_tutors:'Featured Tutors',
  features:'Features',
  timings:'Timings',
  visiting:'Visiting',
  tutors:'Tutors',
  tutor_detail:'Tutor Details',
  company_detail:'Company Details',
  companies:'Companies',
  nannies:'Nannies',
  nannies_detail:'Nannies Detail',
  school_detail:'School Details',
  school:'Schools',
  school_group:'School Group',
  nursery_group:'Nursery Group',
  nursery_detail:'Nursery Detail',
  nursery:'Nurseries',
  latest_review:'Latest Reviews',
  more:'More',
  e_learning_school:'E learning_School',
  recent_event:'Recent Events',
  testimonials:'Testimonials',
  parent_guide:`Parent's Guide`,
  news_events:'News & Events',
  email_us:'Email Us',
  contact_person_name:'Contact Person Name',
  brochure:'Brochure',
  photo_gallery:'Photo Gallery',
  review:'Reviews',
  search:'Search',
};
